version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  express:
    image: node:latest
    volumes:
      - "./express:/app"
    command: "node /app/index.js"
    ports: 
      - "3001:3001"